const products=[
{name:'Kit de Sabonetes Elementos',size:'4 sabonetes · 300g',desc:'Terra, Água, Fogo e Ar reunidos em um ritual botânico artesanal. Quatro sabonetes para experimentar diferentes aromas, texturas e elementos no cuidado diário.',price:24,img:'kit_sabonete.jpg'},
{name:'Pele · Hidratante Corporal',size:'150g',desc:'Hidratação intensa com toque sensorial e confortável. Um cuidado corporal para nutrir, amaciar e transformar a hidratação diária em ritual.',price:79,img:'hidratante.jpeg'},
{name:'Elixir · Óleo Corporal',size:'60ml',desc:'Um ritual nutritivo de óleos vegetais e aroma botânico para massagear, perfumar e envolver a pele em um toque macio e luminoso.',price:44,img:'elixir.jpg'},
{name:'Esfoliante Corporal',size:'150g',desc:'Esfoliação corporal à base de açúcar que combina limpeza e cuidado para renovar o toque da pele e deixar o banho ainda mais sensorial.',price:58,img:'esfoliante.jpg'},
{name:'Repelente Botânico',size:'150ml',desc:'Fórmula botânica com andiroba e uma combinação aromática de óleos essenciais, pensada para acompanhar os momentos ao ar livre.',price:68,img:'repelente.jpg'},
{name:'Xô Coceirinha',size:'7ml',desc:'Blend botânico em formato prático, com calêndula, copaíba e óleos essenciais. Pequeno para levar por perto e usar nos momentos de cuidado.',price:24,img:'xococeirinha.jpg'},
{name:'Bálsamo Cicatrizante',size:'30g',desc:'Bálsamo botânico concentrado, rico em manteiga vegetal, cera e óleos, desenvolvido para o cuidado localizado de áreas que pedem atenção especial.',price:68,img:'balsamo.jpg'},
{name:'Pós-Barba Botânico',size:'30ml',desc:'Um ritual refrescante para depois da lâmina, com calêndula, própolis, aloe ou lavanda e mentol para completar o cuidado da pele após o barbear.',price:24,img:'posbarba.jpeg'},
{name:'Sabão de Barbear',size:'30g',desc:'Sabão artesanal criado para preparar a pele e a barba para a lâmina, trazendo mais cuidado e intenção para um ritual cotidiano.',price:18,img:'barbear.jpeg'},
{name:'Desodorante Botânico',size:'120ml',desc:'Cuidado botânico para a rotina diária, com argila branca e uma combinação aromática de óleos essenciais.',price:29,img:'desodorante.jpeg'},
{name:'Body Splash',size:'120ml',desc:'Névoa perfumada, leve e envolvente para usar ao longo do dia. Um gesto simples que transforma aroma em ritual.',price:49,img:'bodysplash.jpg'}];
function money(v){return 'R$ '+v.toFixed(2).replace('.',',')}function getCart(){return JSON.parse(localStorage.getItem('cart')||'[]')}function updateCartCount(){let n=getCart().reduce((s,i)=>s+i.quantity,0),e=document.getElementById('cart-count');if(e)e.textContent=n}function addToCart(i){let c=getCart(),p=products[i],f=c.find(x=>x.name===p.name);if(f)f.quantity++;else c.push({name:p.name,tamanho:p.size,description:p.desc,price:p.price,img:p.img,quantity:1});localStorage.setItem('cart',JSON.stringify(c));updateCartCount()}function displayProducts(){let e=document.getElementById('product-list');e.innerHTML=products.map((p,i)=>'<article class="product-card"><div class="photo" onclick="openModal('+i+')"><img loading="lazy" src="./images/'+p.img+'" alt="'+p.name+'"></div><div class="product-info"><span class="meta">'+p.size+'</span><h3 onclick="openModal('+i+')">'+p.name+'</h3><p>'+p.desc+'</p><div class="price-row"><span class="price">'+money(p.price)+'</span><button class="add" onclick="addToCart('+i+')">Adicionar</button></div></div></article>').join('')}function openModal(i){let p=products[i],m=document.getElementById('productModal');document.getElementById('modalImage').src='./images/'+p.img;document.getElementById('modalSize').textContent=p.size;document.getElementById('modalTitle').textContent=p.name;document.getElementById('modalDescription').textContent=p.desc;document.getElementById('modalPrice').textContent=money(p.price);document.getElementById('modalAdd').onclick=function(){addToCart(i)};m.classList.add('open');document.body.style.overflow='hidden'}function closeModal(){document.getElementById('productModal').classList.remove('open');document.body.style.overflow=''}document.addEventListener('DOMContentLoaded',function(){displayProducts();updateCartCount()});