const products=[
{name:'Kit de Sabonetes Elementos',size:'4 sabonetes · 300g',desc:'Terra, Água, Fogo e Ar. Um ritual botânico completo, com quatro experiências artesanais.',price:18,img:'kit_sabonete.jpg'},
{name:'Pele · Hidratante Corporal',size:'150g',desc:'Hidratação corporal de textura rica e sensorial, criada para deixar a pele macia e cuidada.',price:75,img:'hidratante.jpeg'},
{name:'Elixir · Óleo Corporal',size:'60ml',desc:'Óleos vegetais e essência botânica em um ritual nutritivo para massagear e perfumar a pele.',price:33,img:'elixir.jpg'},
{name:'Esfoliante Corporal',size:'150g',desc:'Esfoliação sensorial à base de açúcar para renovar o toque da pele durante o banho.',price:58,img:'esfoliante.jpg'},
{name:'Repelente Botânico',size:'150ml',desc:'Fórmula botânica com andiroba e óleos essenciais aromáticos para acompanhar momentos ao ar livre.',price:68,img:'repelente.jpg'},
{name:'Xô Coceirinha',size:'7ml',desc:'Blend prático com calêndula, copaíba e óleos essenciais, em embalagem para levar sempre por perto.',price:23,img:'xococeirinha.jpg'},
{name:'Bálsamo de Cuidado',size:'30g',desc:'Bálsamo concentrado com manteiga vegetal, cera e óleos botânicos para áreas que pedem cuidado.',price:68,img:'balsamo.jpg'},
{name:'Pós-Barba Botânico',size:'30ml',desc:'Calêndula, própolis, aloe ou lavanda e mentol em um ritual refrescante para depois da lâmina.',price:18,img:'posbarba.jpeg'},
{name:'Sabão de Barbear',size:'30g',desc:'Sabão artesanal para preparar o barbear e transformar a rotina em um ritual de cuidado.',price:3,img:'barbear.jpeg'},
{name:'Desodorante Botânico',size:'120ml',desc:'Cuidado diário com argila branca e uma combinação aromática de óleos essenciais.',price:21,img:'desodorante.jpeg'},
{name:'Body Splash',size:'120ml',desc:'Uma névoa perfumada e leve para reaplicar ao longo do dia e criar seu próprio ritual de aroma.',price:48,img:'bodysplash.jpg'}];
function money(v){return 'R$ '+v.toFixed(2).replace('.',',')}function getCart(){return JSON.parse(localStorage.getItem('cart')||'[]')}function updateCartCount(){let n=getCart().reduce((s,i)=>s+i.quantity,0),e=document.getElementById('cart-count');if(e)e.textContent=n}function addToCart(i){let c=getCart(),p=products[i],f=c.find(x=>x.name===p.name);if(f)f.quantity++;else c.push({name:p.name,tamanho:p.size,description:p.desc,price:p.price,img:p.img,quantity:1});localStorage.setItem('cart',JSON.stringify(c));updateCartCount()}function displayProducts(){let e=document.getElementById('product-list');e.innerHTML=products.map((p,i)=>'<article class="product-card"><div class="photo" onclick="openModal('+i+')"><img loading="lazy" src="./images/'+p.img+'" alt="'+p.name+'"></div><div class="product-info"><span class="meta">'+p.size+'</span><h3 onclick="openModal('+i+')">'+p.name+'</h3><p>'+p.desc+'</p><div class="price-row"><span class="price">'+money(p.price)+'</span><button class="add" onclick="addToCart('+i+')">Adicionar</button></div></div></article>').join('')}function openModal(i){let p=products[i],m=document.getElementById('productModal');document.getElementById('modalImage').src='./images/'+p.img;document.getElementById('modalSize').textContent=p.size;document.getElementById('modalTitle').textContent=p.name;document.getElementById('modalDescription').textContent=p.desc;document.getElementById('modalPrice').textContent=money(p.price);document.getElementById('modalAdd').onclick=function(){addToCart(i)};m.classList.add('open');document.body.style.overflow='hidden'}function closeModal(){document.getElementById('productModal').classList.remove('open');document.body.style.overflow=''}document.addEventListener('DOMContentLoaded',function(){displayProducts();updateCartCount()});